Clase1307
BernardoLarsen/CFL2020 pull request #10
Opened 2020-07-22 00:10 UTC by BernardoLarsen

Primer Ejercicio de matriz

2020-07-22 14:29 UTC, rbeltracchi reviewed
Tenes ejercicios de la clase 1 que estas subiendo tambien, esta bien que forme parte de la clase 1307? Actualizaste tu master local antes de sacar este branch?

2020-07-22 16:49 UTC, BernardoLarsen commented
Rodri no me di cuenta que estaba subiendo esto, de todas formas el de registroAutomotor no lo habia subido todavia, le falta algo, pero esta todo dentro de la misma clase, por eso se suben juntos, por mas de que lo tenga mal.. lo que puse mal es que el comentario puse que era de matriz unicamente

2020-07-23 16:59 UTC, mauri52 requested changes

2020-07-23 16:59 UTC, mauri52 commented on IntroPoo/registroAutomotor/registro.ts
> +        arrayRegistro=nuevoAuto.split("");
arrayRegistro=nuevoAuto.split("");
esto funciona?

2020-07-23 16:59 UTC, mauri52 commented on IntroPoo/registroAutomotor/registro.ts
> +    let arrayAutos:string[]=lista("\r\n");
deberia ser: lista.split("\r\n");

2020-07-25 17:03 UTC, BernardoLarsen commented on IntroPoo/registroAutomotor/registro.ts
> +        arrayRegistro=nuevoAuto.split("");
Hola mauricio, nono no funciona, me equivoque de branch, no queria subir esto de registroAuto, ahora voy a subir uno nuevo con el completo de matriz y el de registroAuto bien completo.. mil disulpas

2020-07-25 17:07 UTC, closed without merging